[variables]
PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = [
    "pip install --upgrade pip setuptools==69.0.0 wheel",
    "pip install -r backend/requirements.txt"
]

[phases.build]
cmds = [
    "cd backend && python manage.py collectstatic --noinput"
]

[start]
cmd = "cd backend && python manage.py migrate && gunicorn erp_core.wsgi:application --bind 0.0.0.0:$PORT"
